---
name: modelling-tasks-examples
ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Widentities
  - -Wredundant-constraints
  - -Werror
dependencies:
  - base
  - containers
  - graphviz
  - modelling-tasks
  - pretty-simple
library:
  source-dirs: src
tests:
  modelling-tasks-examples-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - modelling-tasks
      - modelling-tasks-examples
      - HUnit
      - hspec
