name: alloy-cd-od
build-tools:
  - alex
  - happy
ghc-options:
  -Wall
  -Wincomplete-uni-patterns
  -Wincomplete-record-updates
  -Widentities
  -Wredundant-constraints
dependencies:
  - base
  - array
  - bimap
  - containers
  - fgl
  - file-embed
  - filepath
  - graphviz
  - MonadRandom
  - process
  - random
  - random-shuffle
  - split
  - text
library:
  source-dirs: .
  exposed-modules:
    - Alloy
    - Edges
    - Generate
    - Auxiliary.Lexer
    - Mutation
    - Output
    - Auxiliary.Parser
    - RandomTask
    - CD2Alloy.Transform
    - Types
    - Auxiliary.Util
executables:
  cd2alloy:
    main: cd2alloy.hs
    dependencies:
      - time
    other-modules:
      - Auxiliary.Lexer
      - Auxiliary.Parser
      - CD2Alloy.Transform
      - Types
  cd2pic:
    main: cd2pic.hs
    other-modules:
      - Edges
      - Auxiliary.Lexer
      - Output
      - Auxiliary.Parser
      - Types
      - Auxiliary.Util
  different-names:
    main: different-names.hs
    other-modules:
      - Alloy
      - Edges
      - Generate
      - NaiveTasks
      - Output
      - CD2Alloy.Transform
      - Types
      - Auxiliary.Util
  instance2pic:
    main: instance2pic.hs
    other-modules:
      - Edges
      - Output
      - Types
      - Auxiliary.Util
  random-task:
    main: random-task.hs
    dependencies:
      - bytestring
      - digest
    other-modules:
      - Alloy
      - Edges
      - Generate
      - Mutation
      - Output
      - RandomTask
      - CD2Alloy.Transform
      - Types
      - Auxiliary.Util
