name: ba-athena-schulz
extra-source-files: []
dependencies:
  - base
  - bytestring
  - call-alloy-fork
  - containers
  - edit-distance-vector
  - extra
  - file-embed
  - hgal
  - modelling-tasks
  - mtl
  - process
  - random
  - random-shuffle
  - string-interpolate
  - vector
default-extensions:
  - TupleSections
  - DuplicateRecordFields
  - OverloadedLabels
  - MultiParamTypeClasses
  - FlexibleInstances
  - TypeApplications
  - ScopedTypeVariables
library:
  source-dirs: src
  exposed-modules:
    - Modelling.ActivityDiagram.Alloy
    - Modelling.ActivityDiagram.Datatype
    - Modelling.ActivityDiagram.Instance
    - Modelling.ActivityDiagram.PlantUMLConverter
    - CallPlantUML
    - Modelling.ActivityDiagram.Petrinet
    - Modelling.ActivityDiagram.MatchPetri
    - Modelling.ActivityDiagram.MatchAD
    - Modelling.ActivityDiagram.ActionSequences
    - Modelling.ActivityDiagram.Config
    - Modelling.ActivityDiagram.Shuffle
    - Modelling.ActivityDiagram.SelectAS
    - Modelling.ActivityDiagram.EnterAS
    - Modelling.ActivityDiagram.SelectPetri
    - Modelling.ActivityDiagram.Isomorphism
  ghc-options:
    - -Wall
    - -Werror
executables:
  matchToPetri:
    main: matchToPetri.hs
    source-dirs: app
    dependencies:
      - ba-athena-schulz
      - directory
      - filepath
      - graphviz
  selectPetrinet:
    main: selectPetrinet.hs
    source-dirs: app
    dependencies:
      - ba-athena-schulz
      - directory
      - filepath
      - graphviz
  matchADComponents:
    main: matchADComponents.hs
    source-dirs: app
    dependencies:
      - ba-athena-schulz
      - directory
      - filepath
  selectActionSequence:
    main: selectActionSequence.hs
    source-dirs: app
    dependencies:
      - ba-athena-schulz
      - directory
      - filepath
  enterActionSequence:
    main: enterActionSequence.hs
    source-dirs: app
    dependencies:
      - ba-athena-schulz
      - directory
      - filepath
  evalIsomorphic:
    main: evalIsomorphic.hs
    source-dirs: app
    dependencies:
      - ba-athena-schulz
      - directory
      - filepath
  evalTimeToGenerate:
    main: evalTimeToGenerate.hs
    source-dirs: app
    dependencies:
      - ba-athena-schulz
      - filepath
      - criterion-measurement
  default:
    main: default.hs
    source-dirs: app
    dependencies:
      - ba-athena-schulz
tests:
  ba-athena-schulz-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ba-athena-schulz
      - hspec
