name: modelling-tasks
extra-source-files:
  - alloy/cd/assoclimits.als
  - alloy/cd/generate.als
  - alloy/od/template.als
  - alloy/petri/Helpers.als
  - alloy/petri/PetriAdditions.als
  - alloy/petri/PetriConcepts.als
  - alloy/petri/PetriConstraints.als
  - alloy/petri/PetriSignature.als
  - README.md
build-tools:
  - alex
  - happy
ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Widentities
  - -Wredundant-constraints
  - -Werror
  - -Wwarn=incomplete-uni-patterns
  - -Wwarn=orphans
dependencies:
  - MonadRandom
  - SVGFonts
  - base
  - bimap
  - call-alloy >= 0.2.0.4 && < 0.3
  - containers
  - diagrams
  - diagrams-graphviz
  - diagrams-lib
  - diagrams-svg
  - fgl
  - file-embed
  - filepath
  - graphviz
  - latex-svg-image
  - random-shuffle
  - split
  - string-interpolate
  - text
  - transformers
library:
  source-dirs: src
  exposed-modules:
    - Modelling.CdOd.Auxiliary.Util
    - Modelling.CdOd.CD2Alloy.Transform
    - Modelling.CdOd.CdAndChanges.Instance
    - Modelling.CdOd.CdAndChanges.Transform
    - Modelling.CdOd.DifferentNames
    - Modelling.CdOd.Edges
    - Modelling.CdOd.Generate
    - Modelling.CdOd.MatchCdOd
    - Modelling.CdOd.Mutation
    - Modelling.CdOd.Output
    - Modelling.CdOd.RepairCd
    - Modelling.CdOd.SelectValidCd
    - Modelling.CdOd.Types
    - Modelling.PetriNet.Alloy
    - Modelling.PetriNet.Diagram
    - Modelling.PetriNet.LaTeX
    - Modelling.PetriNet.MatchToMath
    - Modelling.PetriNet.Parser
    - Modelling.PetriNet.Types
    - Modelling.PetriNet.ConcurrencyAndConflict
    - Modelling.PetriNet.BasicNetFunctions
executables:
  cd2alloy:
    main: cd2alloy.hs
    source-dirs: legacy-app
    dependencies:
      - array
      - modelling-tasks
      - time
    other-modules:
      - Modelling.CdOd.Auxiliary.Lexer
      - Modelling.CdOd.Auxiliary.Parser
  cd2pic:
    main: cd2pic.hs
    source-dirs: legacy-app
    dependencies:
      - array
      - modelling-tasks
    other-modules:
      - Modelling.CdOd.Auxiliary.Lexer
      - Modelling.CdOd.Auxiliary.Parser
  conflicts:
    main: conflicts.hs
    source-dirs: app
    dependencies:
      - bytestring
      - digest
      - modelling-tasks
      - pretty-simple
  concurrency:
    main: concurrency.hs
    source-dirs: app
    dependencies:
      - bytestring
      - digest
      - modelling-tasks
      - pretty-simple
  different-names:
    main: different-names.hs
    source-dirs: app
    dependencies:
      - bytestring
      - digest
      - modelling-tasks
    other-modules:
      - EvaluateArgs
  instance2pic:
    main: instance2pic.hs
    source-dirs: legacy-app
    dependencies:
      - array
      - modelling-tasks
  match-cd-od:
    main: match-cd-od.hs
    source-dirs: app
    dependencies:
      - bytestring
      - digest
      - modelling-tasks
    other-modules:
      - EvaluateArgs
  matchToMath:
    main: matchToMath.hs
    source-dirs: app
    dependencies:
      - bytestring
      - digest
      - modelling-tasks
      - pretty-simple
  repair-incorrect:
    main: repair-incorrect.hs
    source-dirs: app
    dependencies:
      - bytestring
      - digest
      - modelling-tasks
    other-modules:
      - EvaluateArgs
  check-cds:
    main: check-cds.hs
    source-dirs: app
    dependencies:
      - bytestring
      - digest
      - modelling-tasks
tests:
  modelling-tasks-test:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - modelling-tasks
    - QuickCheck
    - hspec
    - process
    - random
