name: alloy-cd-od
build-tools:
  - alex
  - happy
ghc-options:
  -Wall
  -Wincomplete-uni-patterns
  -Wincomplete-record-updates
  -Widentities
  -Wredundant-constraints
dependencies:
  - base
  - array
  - bimap
  - call-alloy >= 0.2.0.4 && < 0.3
  - containers
  - fgl
  - file-embed
  - filepath
  - graphviz
  - MonadRandom
  - random
  - random-shuffle
  - split
  - string-interpolate
  - text
library:
  source-dirs: src
  exposed-modules:
    - Alloy.CdOd.Auxiliary.Util
    - Alloy.CdOd.CD2Alloy.Transform
    - Alloy.CdOd.CdAndChanges.Instance
    - Alloy.CdOd.CdAndChanges.Transform
    - Alloy.CdOd.Edges
    - Alloy.CdOd.Generate
    - Alloy.CdOd.Mutation
    - Alloy.CdOd.Output
    - Alloy.CdOd.Types
executables:
  cd2alloy:
    main: cd2alloy.hs
    source-dirs: legacy-app
    dependencies:
      - alloy-cd-od
      - time
    other-modules:
      - Alloy.CdOd.Auxiliary.Lexer
      - Alloy.CdOd.Auxiliary.Parser
  cd2pic:
    main: cd2pic.hs
    source-dirs: legacy-app
    dependencies:
      - alloy-cd-od
    other-modules:
      - Alloy.CdOd.Auxiliary.Lexer
      - Alloy.CdOd.Auxiliary.Parser
  different-names:
    main: different-names.hs
    source-dirs: app
    dependencies:
      - alloy-cd-od
    other-modules:
      - Alloy.CdOd.MatchCdOd
      - Alloy.CdOd.NaiveTasks
  instance2pic:
    main: instance2pic.hs
    source-dirs: legacy-app
    dependencies:
      - alloy-cd-od
  match-cd-od:
    main: match-cd-od.hs
    source-dirs: app
    dependencies:
      - alloy-cd-od
      - bytestring
      - digest
    other-modules:
      - Alloy.CdOd.MatchCdOd
  repair-incorrect:
    main: repair-incorrect.hs
    source-dirs: app
    dependencies:
      - alloy-cd-od
    other-modules:
      - Alloy.CdOd.MatchCdOd
      - Alloy.CdOd.NaiveTasks
  check-cds:
    main: check-cds.hs
    source-dirs: app
    dependencies:
      - alloy-cd-od
