name: ba-athena-schulz
extra-source-files: []
dependencies:
  - base
  - bytestring
  - call-alloy
  - call-plantuml
  - containers
  - edit-distance-vector
  - extra
  - file-embed
  - graphviz
  - hgal
  - modelling-tasks
  - MonadRandom
  - mtl
  - output-monad
  - process
  - random
  - random-shuffle
  - string-interpolate
  - vector
default-extensions:
  - TupleSections
  - DuplicateRecordFields
  - OverloadedLabels
  - MultiParamTypeClasses
  - FlexibleInstances
  - TypeApplications
  - ScopedTypeVariables
library:
  source-dirs: src
  exposed-modules:
    - Modelling.ActivityDiagram.Auxiliary.Util
    - Modelling.ActivityDiagram.Alloy
    - Modelling.ActivityDiagram.Datatype
    - Modelling.ActivityDiagram.Instance
    - Modelling.ActivityDiagram.PlantUMLConverter
    - Modelling.ActivityDiagram.Petrinet
    - Modelling.ActivityDiagram.MatchPetri
    - Modelling.ActivityDiagram.MatchAD
    - Modelling.ActivityDiagram.ActionSequences
    - Modelling.ActivityDiagram.Config
    - Modelling.ActivityDiagram.Shuffle
    - Modelling.ActivityDiagram.SelectAS
    - Modelling.ActivityDiagram.EnterAS
    - Modelling.ActivityDiagram.SelectPetri
    - Modelling.ActivityDiagram.FindSupportST
    - Modelling.ActivityDiagram.Isomorphism
  ghc-options:
    - -Wall
    - -Werror
executables:
  evalIsomorphic:
    main: evalIsomorphic.hs
    source-dirs: app
    dependencies:
      - ba-athena-schulz
      - directory
      - filepath
  evalTimeToGenerate:
    main: evalTimeToGenerate.hs
    source-dirs: app
    dependencies:
      - ba-athena-schulz
      - filepath
      - criterion-measurement
  selectASTaskDemo:
    main: selectASTaskDemo.hs
    source-dirs:
      - app
      - app/common
    dependencies:
      - ba-athena-schulz
  selectPetriTaskDemo:
    main: selectPetriTaskDemo.hs
    source-dirs:
      - app
      - app/common
    dependencies:
      - ba-athena-schulz
  findSupportSTTaskDemo:
    main: findSupportSTTaskDemo.hs
    source-dirs:
      - app
      - app/common
    dependencies:
      - ba-athena-schulz
  enterASTaskDemo:
    main: enterASTaskDemo.hs
    source-dirs:
      - app
      - app/common
    dependencies:
      - ba-athena-schulz
  matchADTaskDemo:
    main: matchADTaskDemo.hs
    source-dirs:
      - app
      - app/common
    dependencies:
      - ba-athena-schulz
  matchPetriTaskDemo:
    main: matchPetriTaskDemo.hs
    source-dirs:
      - app
      - app/common
    dependencies:
      - ba-athena-schulz
tests:
  ba-athena-schulz-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ba-athena-schulz
      - hspec
