name: petri-tasks
dependencies:
  - base
  - call-alloy
  - string-interpolate
  - containers
  - transformers
  - file-embed
library:
  source-dirs: .
  exposed-modules: 
    - Functions
    - Interactions
    - AuxFunctions
    - PetriParser