name: petri-tasks
extra-source-files:
  - lib/Alloy/Helpers.als
  - lib/Alloy/PetriAdditions.als
  - lib/Alloy/PetriConcepts.als
  - lib/Alloy/PetriConstraints.als
  - lib/Alloy/PetriSignature.als
dependencies:
  - base
  - call-alloy
  - diagrams
  - diagrams-lib
  - diagrams-graphviz
  - diagrams-svg
  - file-embed
  - fgl
  - graphviz
  - HaTeX
  - string-interpolate
  - SVGFonts
  - containers
  - transformers
  - text
  - pretty-simple
library:
  source-dirs: src
  exposed-modules: 
    - Modelling.PetriNet.Alloy
    - Modelling.PetriNet.Diagram
    - Modelling.PetriNet.LaTeX
    - Modelling.PetriNet.MatchToMath
    - Modelling.PetriNet.Parser
    - Modelling.PetriNet.Types
    - Modelling.PetriNet.Conflicts
    - Modelling.PetriNet.Concurrency
    - Modelling.PetriNet.BasicNetFunctions
  ghc-options:
    - -Wall
    - -Werror
executables:
  matchToMath:
    main: matchToMath.hs
    source-dirs: app
    dependencies:
      - petri-tasks
  conflicts:
    main: conflicts.hs
    source-dirs: app
    dependencies:
      - petri-tasks
  concurrency:
    main: concurrency.hs
    source-dirs: app
    dependencies:
      - petri-tasks
tests:
  petri-tasks-test:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - petri-tasks
    - hspec
    - process
