name: petri-tasks
extra-source-files:
  - lib/Alloy/Helpers.als
  - lib/Alloy/OneLiners.als
  - lib/Alloy/PetriAdditions.als
  - lib/Alloy/PetriConcepts.als
  - lib/Alloy/PetriConstraints.als
  - lib/Alloy/PetriSignature.als
dependencies:
  - base
  - call-alloy
  - diagrams
  - diagrams-lib
  - diagrams-graphviz
  - diagrams-svg
  - file-embed
  - fgl
  - graphviz
  - HaTeX
  - string-interpolate
  - SVGFonts
  - containers
  - transformers
library:
  source-dirs: .
  exposed-modules: 
    - PetriDiagram
    - AuxFunctions
    - PetriParser
    - PetriAlloy
    - Inputs
    - Types
  ghc-options:
    - -Wall
    - -Werror
tests:
  petri-tasks-test:
    main: Spec.hs
    source-dirs:
    - .
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - petri-tasks
    - hspec
    - QuickCheck
