name: ba-athena-schulz
extra-source-files: []
dependencies:
  - base
  - call-alloy
  - containers
  - extra
  - mtl
default-extensions:
  - TupleSections
  - DuplicateRecordFields
  - OverloadedLabels
  - MultiParamTypeClasses
  - FlexibleInstances
  - TypeApplications
  - ScopedTypeVariables
library:
  source-dirs: src
  exposed-modules: []
  ghc-options:
    - -Wall
    - -Werror
executables:
  default:
    main: default.hs
    source-dirs: app
    dependencies:
      - ba-athena-schulz
tests:
  ba-athena-schulz-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ba-athena-schulz
      - hspec
