name: petri-tasks
dependencies:
  - base
  - call-alloy
  - diagrams
  - diagrams-lib
  - diagrams-graphviz
  - diagrams-svg
  - file-embed
  - fgl
  - graphviz
  - string-interpolate
  - SVGFonts
  - containers
  - transformers
library:
  source-dirs: .
  exposed-modules: 
    - PetriDiagram
    - AuxFunctions
    - PetriParser
    - Inputs
    - Types