name: alloy-cd-od
build-tools:
  - alex
  - happy
ghc-options:
  -Wall
  -Wincomplete-uni-patterns
  -Wincomplete-record-updates
  -Widentities
  -Wredundant-constraints
dependencies:
  - base
  - array
  - containers
  - fgl
  - file-embed
  - filepath
  - graphviz
  - MonadRandom
  - process
  - random
  - random-shuffle
  - split
  - text
library:
  source-dirs: .
  exposed-modules:
    - Alloy
    - Edges
    - Generate
    - Lexer
    - Mutation
    - Output
    - Parser
    - RandomTask
    - Transform
    - Types
    - Util
executables:
  cd2alloy:
    main: cd2alloy.hs
    dependencies:
      - time
    other-modules:
      - Lexer
      - Parser
      - Transform
      - Types
  cd2pic:
    main: cd2pic.hs
    other-modules:
      - Edges
      - Lexer
      - Output
      - Parser
      - Types
      - Util
  instance2pic:
    main: instance2pic.hs
    other-modules:
      - Edges
      - Output
      - Types
      - Util
  random-task:
    main: random-task.hs
    other-modules:
      - Alloy
      - Edges
      - Generate
      - Mutation
      - Output
      - RandomTask
      - Transform
      - Types
      - Util
