name: alloy-cd-od
build-tools:
  - alex
  - happy
ghc-options:
  -Wall
  -Wincomplete-uni-patterns
  -Wincomplete-record-updates
  -Widentities
  -Wredundant-constraints
dependencies:
  - base
  - array
  - bimap
  - containers
  - fgl
  - file-embed
  - filepath
  - graphviz
  - MonadRandom
  - parsec
  - process
  - random
  - random-shuffle
  - split
  - string-interpolate
  - text
library:
  source-dirs: src
  exposed-modules:
    - Alloy
    - CD2Alloy.Transform
    - CdAndChanges.Instance
    - CdAndChanges.Transform
    - Edges
    - Generate
    - Mutation
    - Output
    - Parser
    - Types
    - Auxiliary.Util
executables:
  cd2alloy:
    main: cd2alloy.hs
    source-dirs: legacy-app
    dependencies:
      - alloy-cd-od
      - time
    other-modules:
      - Auxiliary.Lexer
      - Auxiliary.Parser
  cd2pic:
    main: cd2pic.hs
    source-dirs: legacy-app
    dependencies:
      - alloy-cd-od
    other-modules:
      - Auxiliary.Lexer
      - Auxiliary.Parser
  different-names:
    main: different-names.hs
    source-dirs: app
    dependencies:
      - alloy-cd-od
    other-modules:
      - MatchCdOd
      - NaiveTasks
  instance2pic:
    main: instance2pic.hs
    source-dirs: legacy-app
    dependencies:
      - alloy-cd-od
  match-cd-od:
    main: match-cd-od.hs
    source-dirs: app
    dependencies:
      - alloy-cd-od
      - bytestring
      - digest
    other-modules:
      - MatchCdOd
  repair-incorrect:
    main: repair-incorrect.hs
    source-dirs: app
    dependencies:
      - alloy-cd-od
    other-modules:
      - MatchCdOd
      - NaiveTasks
