---
resolver: lts-21.25
packages:
  - .
flags:
  modelling-tasks:
    alloy-use-sat4j: false
    quick-testing: true
extra-deps:
  - git: https://github.com/fmidue/output-blocks.git
    commit: af1ac8d1f62cb9f739919de1e9bc7989a2c61c95
    subdirs:
      - output-blocks
  - git: https://github.com/fmidue/autotool-capabilities.git
    commit: 8067088f23759d787c049677a26868df26c1676f
    subdirs:
      - autotool-capabilities
      - autotool-capabilities-io-instances
  - call-alloy-0.6.0.2
  - call-plantuml-0.0.1.3
  - diagrams-graphviz-1.4.1.1@sha256:e71afa8f89904c2a6a2cb490dba7108c6425779c2174b90bd90dbaf507a9d3dc,1388
  - hgal-2.0.0.3@sha256:939908a4c80f8bec648043712617cc5794aeba81f7bcad0f77a4e3564da6e4f6,1856
  - latex-svg-image-0.2@sha256:b282a74a96724037ec3d24b664118e51170c8152aff12f363ddb715a38ef053a,1830
allow-newer: true
allow-newer-deps:
  - diagrams-graphviz
  - latex-svg-image
hpack-force: true
