---
name: modelling-task-legacy-apps
build-tools:
  - alex
  - happy
ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Widentities
  - -Wredundant-constraints
  - -Werror
  - -Wwarn=incomplete-uni-patterns
  - -Wwarn=orphans
dependencies:
  - base
executables:
  cd2alloy:
    main: cd2alloy.hs
    source-dirs:
      - .
      - parser
    dependencies:
      - array
      - modelling-tasks
      - time
    other-modules:
      - Modelling.CdOd.Auxiliary.Lexer
      - Modelling.CdOd.Auxiliary.Parser
  cd2pic:
    main: cd2pic.hs
    source-dirs:
      - .
      - parser
    dependencies:
      - array
      - diagrams-lib
      - graphviz
      - modelling-tasks
    other-modules:
      - Modelling.CdOd.Auxiliary.Lexer
      - Modelling.CdOd.Auxiliary.Parser
  different-names-legacy:
    main: different-names.hs
    source-dirs:
      - .
      - ../app/common
      - generate
    dependencies:
      - MonadRandom
      - bytestring
      - call-alloy
      - containers
      - diagrams-lib
      - diagrams-svg
      - digest
      - graphviz
      - modelling-tasks
      - mtl
      - output-monad
      - random-shuffle
      - transformers
    other-modules:
      - Common
      - EvaluateArgs
      - Modelling.CdOd.Generate.DifferentNames
      - Modelling.CdOd.Generate.Generate
  instance2pic:
    main: instance2pic.hs
    source-dirs: .
    dependencies:
      - MonadRandom
      - array
      - containers
      - graphviz
      - modelling-tasks
  match-cd-od-legacy:
    main: match-cd-od.hs
    source-dirs:
      - .
      - ../app/common
      - generate
    dependencies:
      - MonadRandom
      - bytestring
      - call-alloy
      - containers
      - diagrams-lib
      - diagrams-svg
      - digest
      - graphviz
      - modelling-tasks
      - mtl
      - output-monad
      - random-shuffle
      - transformers
    other-modules:
      - Common
      - EvaluateArgs
      - Modelling.CdOd.Generate.Generate
      - Modelling.CdOd.Generate.MatchCdOd
      - Modelling.CdOd.Generate.Mutation
