---
name: Consistency Checks

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  consistency:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: stack.yaml has no additions to stack-examples.yaml
        run: "! comm -23 stack.yaml stack-examples.yaml | grep ."

      - name: stack-examples.yaml has no additions to stack-apps.yaml
        run: "! comm -23 stack-examples.yaml stack-apps.yaml | grep ."

      - name: stack-apps.yaml has some additions to stack-example.yaml
        run: "comm -13 stack-examples.yaml stack-apps.yaml | grep ."

      - name: stack-examples.yaml has some additions to stack.yaml
        run: "comm -13 stack.yaml stack-examples.yaml | grep ."
