---
name: Haskell Linter

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Set up HLint'
        uses: haskell/actions/hlint-setup@v2
        with:
          version: '3.5'

      - name: 'Run HLint'
        uses: haskell/actions/hlint-run@v2
        with:
          path: '["src/", "test/", "app/"]'
          fail-on: suggestion
